# Inspired from sunfloxcz/docker-php-build (https://hub.docker.com/r/sunfoxcz/docker-php-build/)

FROM ubuntu:16.04
MAINTAINER Vojtěch Mareš <vojta.mares@fiolasoft.cz>

ADD image /build

# bower: cache
ENV YARN_CACHE_FOLDER /cache/yarn

# Configure Composer
ENV COMPOSER_CACHE_DIR /cache/composer
ENV COMPOSER_NO_INTERACTION 1

# Composer: make global packages available for execution
ENV PATH $PATH:~/.composer/vendor/bin

RUN /build/prepare.sh && \
	/build/system_services.sh && \
	/build/packages.sh 7.2 && \
	/build/cleanup.sh

CMD ["/sbin/my_init"]